const SQUARE_SIZE = 30;

const NUMBER_OF_ROWS = 21;
const NUMBER_OF_COLS = 35;

const START_NODE_ROW = 10;
const START_NODE_COL = 8;
const FINISH_NODE_ROW = 10;
const FINISH_NODE_COL = 26;

export {
  NUMBER_OF_COLS,
  NUMBER_OF_ROWS,
  SQUARE_SIZE,
  START_NODE_COL,
  START_NODE_ROW,
  FINISH_NODE_COL,
  FINISH_NODE_ROW,
};
